export const tableData = [
  {
    category: "General",
    basic: true,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "Number of sites",
        basic: "1",
        business: "5",
        pro: "15",
      },
      {
        subcategory: "Media manager",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "3rd party integrations",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Team members",
        basic: "0",
        business: "3",
        pro: "10",
      },
      {
        subcategory: "'Powered by' logo",
        basic: "Always active",
        business: "Optional",
        pro: "Optional",
      },
    ],
  },
  {
    category: "Funnel Builder",
    basic: true,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "Number of funnels",
        basic: "10",
        business: "100",
        pro: "500",
      },
      {
        subcategory: "Number of template groups",
        basic: "5",
        business: "15",
        pro: "99999",
      },
      {
        subcategory: "Mobile optimizer",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "In-built conversion tools",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Html download",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Save as template",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Clone page",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Unique visitors",
        basic: "25,000",
        business: "100,000",
        pro: "Unlimited",
      },
      {
        subcategory: "Transfer funnels",
        basic: false,
        business: false,
        pro: true,
      },
    ],
  },
  {
    category: "Product Builder",
    basic: true,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "Number of products",
        basic: "10",
        business: "50",
        pro: "250",
      },
      {
        subcategory: "Membership module products",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Digital products",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Instasuite checkout",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Multiple price points",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Coupons and discounts",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Automation actions",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Digital delivery - Email",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Digital delivery - URL",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Digital delivery - File",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Digital delivery - ISPDN",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Export orders to csv",
        basic: true,
        business: true,
        pro: true,
      },
    ],
  },
  {
    category: "Membership Builder",
    basic: true,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "In-built SMTP",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Number of themes",
        basic: "1",
        business: "3",
        pro: "5",
      },
      {
        subcategory: "Number of members",
        basic: "1,000",
        business: "5,000",
        pro: "100,000",
      },
      {
        subcategory: "Member tags",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Drip-feed",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Member progress tracking",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Quiz tracking",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Design editor",
        basic: true,
        business: true,
        pro: true,
      },
    ],
  },
  {
    category: "List Builder",
    basic: true,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "SMTP setup",
        basic: "Own",
        business: "Own",
        pro: "Own",
      },
      {
        subcategory: "Blacklist domain, email, IP",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Block role-based email",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Number of lists",
        basic: "10",
        business: "100",
        pro: "Unlimited",
      },
      {
        subcategory: "Number of subscribers",
        basic: "1,000",
        business: "5,000",
        pro: "100,000",
      },
      {
        subcategory: "Manual/Bulk import",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "List segmentation",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Automations",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Optin forms",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Broadcasts",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Sequences",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Save email templates",
        basic: true,
        business: true,
        pro: true,
      },
    ],
  },
  {
    category: "Blog Builder",
    basic: true,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "Widgets",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Menu",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Theme customization",
        basic: true,
        business: true,
        pro: true,
      },
      {
        subcategory: "Number of themes",
        basic: "1",
        business: "3",
        pro: "3",
      },
      {
        subcategory: "Number of posts",
        basic: "Unlimited",
        business: "Unlimited",
        pro: "Unlimited",
      },
      {
        subcategory: "Post categories",
        basic: true,
        business: true,
        pro: true,
      },
    ],
  },
  {
    category: "Affiliate Center",
    basic: false,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "In-built SMTP",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Promotion tools",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Manage commissions",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Number of affiliates",
        basic: '0',
        business: '1,000',
        pro: '5,000',
      },
      {
        subcategory: "Number of themes",
        basic: '0',
        business: '1',
        pro: '1',
      },
      {
        subcategory: "Theme customization",
        basic: false,
        business: true,
        pro: true,
      },
    ],
  },
  {
    category: "Support Desk",
    basic: false,
    business: true,
    pro: true,
    accordian: [
      {
        subcategory: "Number of staff",
        basic: '0',
        business: '3',
        pro: '10',
      },
      {
        subcategory: "In-built SMTP",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Number of canned responses",
        basic: '0',
        business: '20',
        pro: '100',
      },
      {
        subcategory: "Knowledgebase",
        basic: false,
        business: true,
        pro: true,
      },
      {
        subcategory: "Number of themes",
        basic: '0',
        business: '1',
        pro: '1',
      },
    ],
  },
];

export const planData = [
  {
    plan: 'basic',
    price: '297'
  },
  {
    plan: 'business',
    price: '697'
  },
  {
    plan: 'pro',
    price: '997'
  },
]
